<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="personService"
  targetNamespace="http://com.cubic.net/personservice/1.0"
  xmlns:tns="http://com.cubic.net/personservice/1.0" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
  xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  
  <wsdl:types>
    <xsd:schema targetNamespace="http://com.cubic.net/personservice/1.0">
      <xsd:import schemaLocation="PersonService.xsd"
        namespace="http://com.cubic.net/personservice/1.0" />
    </xsd:schema>
  </wsdl:types>
  
  <wsdl:message name="PersonServiceRequest">
    <wsdl:part name="PersonServiceRequest" element="tns:PersonServiceRequest" />
  </wsdl:message>
  
  <wsdl:message name="PersonServiceResponse">
    <wsdl:part name="PersonServiceResponse" element="tns:PersonServiceResponse" />
  </wsdl:message>
  
  <wsdl:portType name="PersonServicePortType">
    <wsdl:operation name="searchPerson">
      <wsdl:input name="PersonServiceRequest" message="tns:PersonServiceRequest" />
      <wsdl:output name="PersonServiceResponse" message="tns:PersonServiceResponse" />
    </wsdl:operation>
  </wsdl:portType>
  
  <wsdl:binding name="PersonServiceBinding" type="tns:PersonServicePortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http" />
    <wsdl:operation name="searchPerson">
      <soap:operation style="document" soapAction="http://com.cubic.net/PersonService/getPerson" />
      <wsdl:input name="PersonServiceRequest">
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output name="PersonServiceResponse">
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  
  <wsdl:service name="PersonService">
    <wsdl:port name="PersonServicePort" binding="tns:PersonServiceBinding">
      <soap:address location="/service/personService" />
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>